# Generated by Django 5.1.1 on 2024-09-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='toys',
            field=models.ManyToManyField(to='my_app.toy'),
        ),
    ]
